### PR TITLE
global: workflows import fixes

### PR DESCRIPTION
**Pull request by jmartinm**
* Fixes imports due to separation of invenio-workflows.

* Adds invenio-workflows dependency to setup.py.

Signed-off-by: Javier Martin Montull <javier.martin.montull@cern.ch>

### CODE REVIEW

**Comment by jmartinm** [comment]
I see there is an error in the tests regarding the import of the testsuite, will fix it and repush.

**Comment by jmartinm** [comment]
The problem is that https://github.com/inveniosoftware/invenio-workflows does not have a `tests` package anymore but [the tests](https://github.com/inveniosoftware/invenio-oaiharvester/pull/10/files#diff-66fab2bff45b30294f29955a303fc6c3R22) try to import them.

What shall we do [with this](https://github.com/inveniosoftware/invenio-oaiharvester/pull/10/files#diff-66fab2bff45b30294f29955a303fc6c3R22) @jalavik ?

**Comment by jalavik** [comment]
@jmartinm  Ouch, one would need to port the `WorkflowTasksTestCase` to `invenio-oaiharvester` tests. Making it like `OAIHarvesterTestCase`.

**Comment by jmartinm** [comment]
After checking with @jalavik seems like we don't need `test_tasks.py` so I have removed it. Let's see if tests pass.

**Comment by jirikuncar** [comment]
@jmartinm please add `FIX` label to commit message. Thanks

**Comment by jmartinm** [comment]
Done.

**Pull request merged**
