### PR TITLE
feat: add encoding support

### PR DESCRIPTION
**Pull request by jma**
Signed-off-by: Johnny Mariéthoz <Johnny.Mariethoz@rero.ch>

### CODE REVIEW

**Comment by jma** [comment]
isort failed on travis but works nice on my machine. Any ideas?

**Comment by jacquerie** [comment]
> isort failed on travis but works nice on my machine. Any ideas?

Two ideas:
1. Make sure that the version of `isort` matches.
2. Make sure that you're installing exactly the same packages, as `isort` will report different things on where an import should be if the package is not installed.

**Comment by jacquerie** [comment]
It's probably 2., given that it's complaining about `invenio_db`, and you don't install it in the `all` extra (but you install it by choosing which DB backend to use, e.g. `$ pip install -e .[all,sqlite3]`.)

**Comment by jma** [comment]
You are right: isort version matches, thus it is 2!
But `invenio-db` is installed...
I created a virtualenv from scratch and follows the travis steps and solved isort errors. I hope it will works!

**Comment by jma** [comment]
Seems ok.

**Comment by jma** [comment]
Any news?

**Comment by jacquerie** [comment]
I just noticed a question of which I happened to know the answer to, @david-caro is probably the person who should be looking at this.

**Comment by david-caro** [comment]
Looks good to me :), thanks for the PR!

**Comment by david-caro** [comment]
Do you need this feature? I can do a release if that helps.

**Comment by jma** [comment]
@david-caro Yes, it is require for RERO DOC. Thanks for the merge.

**Pull request merged**
